coala.less: Deprecated selectors updated
coala/coala-atom pull request #36
Opened 2017-01-17 16:36 UTC by RohanVB

The automatic translation of selectors
will be removed in a few release cycles of atom.
Hence they needed to be upgraded.

Fixes https://github.com/coala/coala-atom/issues/35

2017-02-06 15:50 UTC, RohanVB commented
Will check up on this in a bit.

2017-02-07 03:04 UTC, meetmangukiya requested changes

2017-02-07 03:04 UTC, meetmangukiya commented on styles/coala.less
>  @import "ui-variables";
Change in log:
```diff
-- Hence they needed to be upgraded.
++ Hence, they need ...
```

2017-02-07 07:07 UTC, RohanVB commented
Think I deleted it locally, ref: https://github.com/coala/coala-atom/pull/41

2017-02-07 07:07 UTC, closed without merging